"""add public workshops brands and idempotency

Revision ID: 20260724_0009
Revises: 20260724_0008
Create Date: 2026-07-24 18:27:53.995556
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import inspire_flow_backend.data.types

revision: str = "20260724_0009"
down_revision: str | Sequence[str] | None = "20260724_0008"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

VISIBILITY_VALUES = "('private', 'workshop_public', 'brands_only', 'authorized_brands')"


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "brand_organizations",
        sa.Column("id", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("website_url", sa.String(length=2048), nullable=True),
        sa.Column("logo_url", sa.String(length=2048), nullable=True),
        sa.Column("created_by_user_id", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column("created_at", inspire_flow_backend.data.types.UTCDateTime(), nullable=False),
        sa.Column("updated_at", inspire_flow_backend.data.types.UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_brand_organizations_created_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_brand_organizations")),
    )
    with op.batch_alter_table("brand_organizations", schema=None) as batch_op:
        batch_op.create_index("ix_brand_organizations_updated_at", ["updated_at"], unique=False)

    op.create_table(
        "creator_workshops",
        sa.Column("user_id", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column(
            "status", sa.String(length=16), server_default=sa.text("'draft'"), nullable=False
        ),
        sa.Column("nickname", sa.String(length=50), nullable=False),
        sa.Column("avatar_url", sa.String(length=2048), nullable=True),
        sa.Column("title", sa.String(length=120), nullable=True),
        sa.Column("bio", sa.Text(), nullable=True),
        sa.Column("creator_identity", sa.String(length=100), nullable=True),
        sa.Column("content_focus", sa.Text(), server_default=sa.text("'[]'"), nullable=False),
        sa.Column("collaboration_preferences", sa.Text(), nullable=True),
        sa.Column("nickname_visibility", sa.String(length=32), nullable=False),
        sa.Column("avatar_visibility", sa.String(length=32), nullable=False),
        sa.Column("title_visibility", sa.String(length=32), nullable=False),
        sa.Column("bio_visibility", sa.String(length=32), nullable=False),
        sa.Column("creator_identity_visibility", sa.String(length=32), nullable=False),
        sa.Column("content_focus_visibility", sa.String(length=32), nullable=False),
        sa.Column("collaboration_preferences_visibility", sa.String(length=32), nullable=False),
        sa.Column("published_revision_id", sa.Uuid(native_uuid=False), nullable=True),
        sa.Column("published_at", inspire_flow_backend.data.types.UTCDateTime(), nullable=True),
        sa.Column("created_at", inspire_flow_backend.data.types.UTCDateTime(), nullable=False),
        sa.Column("updated_at", inspire_flow_backend.data.types.UTCDateTime(), nullable=False),
        sa.CheckConstraint(
            f"avatar_visibility IN {VISIBILITY_VALUES}",
            name=op.f("ck_creator_workshops_avatar_visibility_valid"),
        ),
        sa.CheckConstraint(
            "bio_visibility IN ('private', 'workshop_public', 'brands_only', 'authorized_brands')",
            name=op.f("ck_creator_workshops_bio_visibility_valid"),
        ),
        sa.CheckConstraint(
            f"collaboration_preferences_visibility IN {VISIBILITY_VALUES}",
            name=op.f("ck_creator_workshops_collaboration_preferences_visibility_valid"),
        ),
        sa.CheckConstraint(
            f"content_focus_visibility IN {VISIBILITY_VALUES}",
            name=op.f("ck_creator_workshops_content_focus_visibility_valid"),
        ),
        sa.CheckConstraint(
            f"creator_identity_visibility IN {VISIBILITY_VALUES}",
            name=op.f("ck_creator_workshops_creator_identity_visibility_valid"),
        ),
        sa.CheckConstraint(
            f"nickname_visibility IN {VISIBILITY_VALUES}",
            name=op.f("ck_creator_workshops_nickname_visibility_valid"),
        ),
        sa.CheckConstraint(
            "status IN ('draft', 'published', 'withdrawn')",
            name=op.f("ck_creator_workshops_status_valid"),
        ),
        sa.CheckConstraint(
            f"title_visibility IN {VISIBILITY_VALUES}",
            name=op.f("ck_creator_workshops_title_visibility_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_creator_workshops_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_creator_workshops")),
    )
    with op.batch_alter_table("creator_workshops", schema=None) as batch_op:
        batch_op.create_index(
            "ix_creator_workshops_status_updated_at", ["status", "updated_at"], unique=False
        )

    op.create_table(
        "brand_follows",
        sa.Column("id", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column("brand_id", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column("creator_user_id", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column(
            "status", sa.String(length=16), server_default=sa.text("'active'"), nullable=False
        ),
        sa.Column("followed_at", inspire_flow_backend.data.types.UTCDateTime(), nullable=False),
        sa.Column("unfollowed_at", inspire_flow_backend.data.types.UTCDateTime(), nullable=True),
        sa.Column("created_at", inspire_flow_backend.data.types.UTCDateTime(), nullable=False),
        sa.Column("updated_at", inspire_flow_backend.data.types.UTCDateTime(), nullable=False),
        sa.CheckConstraint(
            "status IN ('active', 'inactive')", name=op.f("ck_brand_follows_status_valid")
        ),
        sa.ForeignKeyConstraint(
            ["brand_id"],
            ["brand_organizations.id"],
            name=op.f("fk_brand_follows_brand_id_brand_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["creator_user_id"],
            ["users.id"],
            name=op.f("fk_brand_follows_creator_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_brand_follows")),
        sa.UniqueConstraint(
            "brand_id", "creator_user_id", name="uq_brand_follows_brand_id_creator_user_id"
        ),
    )
    with op.batch_alter_table("brand_follows", schema=None) as batch_op:
        batch_op.create_index(
            "ix_brand_follows_brand_id_status", ["brand_id", "status"], unique=False
        )
        batch_op.create_index(
            "ix_brand_follows_creator_user_id_updated_at",
            ["creator_user_id", "updated_at"],
            unique=False,
        )

    op.create_table(
        "brand_interests",
        sa.Column("id", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column("brand_id", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column("creator_user_id", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column("message", sa.Text(), nullable=True),
        sa.Column(
            "status", sa.String(length=16), server_default=sa.text("'pending'"), nullable=False
        ),
        sa.Column("created_by_user_id", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column("responded_at", inspire_flow_backend.data.types.UTCDateTime(), nullable=True),
        sa.Column("created_at", inspire_flow_backend.data.types.UTCDateTime(), nullable=False),
        sa.Column("updated_at", inspire_flow_backend.data.types.UTCDateTime(), nullable=False),
        sa.CheckConstraint(
            "status IN ('pending', 'accepted', 'declined', 'withdrawn')",
            name=op.f("ck_brand_interests_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["brand_id"],
            ["brand_organizations.id"],
            name=op.f("fk_brand_interests_brand_id_brand_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_brand_interests_created_by_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["creator_user_id"],
            ["users.id"],
            name=op.f("fk_brand_interests_creator_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_brand_interests")),
    )
    with op.batch_alter_table("brand_interests", schema=None) as batch_op:
        batch_op.create_index(
            "ix_brand_interests_brand_id_status", ["brand_id", "status"], unique=False
        )
        batch_op.create_index(
            "ix_brand_interests_creator_user_id_updated_at",
            ["creator_user_id", "updated_at"],
            unique=False,
        )
        batch_op.create_index(
            "uq_brand_interests_pending",
            ["brand_id", "creator_user_id"],
            unique=True,
            sqlite_where=sa.text("status = 'pending'"),
        )

    op.create_table(
        "brand_invitations",
        sa.Column("id", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column("brand_id", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column("invited_user_id", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column("invited_by_user_id", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column(
            "status", sa.String(length=16), server_default=sa.text("'pending'"), nullable=False
        ),
        sa.Column("responded_at", inspire_flow_backend.data.types.UTCDateTime(), nullable=True),
        sa.Column("created_at", inspire_flow_backend.data.types.UTCDateTime(), nullable=False),
        sa.Column("updated_at", inspire_flow_backend.data.types.UTCDateTime(), nullable=False),
        sa.CheckConstraint(
            "status IN ('pending', 'accepted', 'declined', 'revoked')",
            name=op.f("ck_brand_invitations_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["brand_id"],
            ["brand_organizations.id"],
            name=op.f("fk_brand_invitations_brand_id_brand_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["invited_by_user_id"],
            ["users.id"],
            name=op.f("fk_brand_invitations_invited_by_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["invited_user_id"],
            ["users.id"],
            name=op.f("fk_brand_invitations_invited_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_brand_invitations")),
    )
    with op.batch_alter_table("brand_invitations", schema=None) as batch_op:
        batch_op.create_index(
            "ix_brand_invitations_brand_id_status", ["brand_id", "status"], unique=False
        )
        batch_op.create_index(
            "ix_brand_invitations_invited_user_id_status",
            ["invited_user_id", "status"],
            unique=False,
        )
        batch_op.create_index(
            "uq_brand_invitations_pending",
            ["brand_id", "invited_user_id"],
            unique=True,
            sqlite_where=sa.text("status = 'pending'"),
        )

    op.create_table(
        "brand_memberships",
        sa.Column("id", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column("brand_id", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column("user_id", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column("role", sa.String(length=16), server_default=sa.text("'member'"), nullable=False),
        sa.Column("created_at", inspire_flow_backend.data.types.UTCDateTime(), nullable=False),
        sa.CheckConstraint(
            "role IN ('owner', 'member')", name=op.f("ck_brand_memberships_role_valid")
        ),
        sa.ForeignKeyConstraint(
            ["brand_id"],
            ["brand_organizations.id"],
            name=op.f("fk_brand_memberships_brand_id_brand_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_brand_memberships_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_brand_memberships")),
        sa.UniqueConstraint("brand_id", "user_id", name="uq_brand_memberships_brand_id_user_id"),
    )
    with op.batch_alter_table("brand_memberships", schema=None) as batch_op:
        batch_op.create_index(
            "ix_brand_memberships_user_id_brand_id", ["user_id", "brand_id"], unique=False
        )

    op.create_table(
        "creator_inbox_items",
        sa.Column("id", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column("creator_user_id", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column("brand_id", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("reference_id", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column("is_read", sa.Boolean(), server_default=sa.text("0"), nullable=False),
        sa.Column("read_at", inspire_flow_backend.data.types.UTCDateTime(), nullable=True),
        sa.Column("event_at", inspire_flow_backend.data.types.UTCDateTime(), nullable=False),
        sa.Column("created_at", inspire_flow_backend.data.types.UTCDateTime(), nullable=False),
        sa.Column("updated_at", inspire_flow_backend.data.types.UTCDateTime(), nullable=False),
        sa.CheckConstraint(
            "kind IN ('follow', 'interest')", name=op.f("ck_creator_inbox_items_kind_valid")
        ),
        sa.ForeignKeyConstraint(
            ["brand_id"],
            ["brand_organizations.id"],
            name=op.f("fk_creator_inbox_items_brand_id_brand_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["creator_user_id"],
            ["users.id"],
            name=op.f("fk_creator_inbox_items_creator_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_creator_inbox_items")),
        sa.UniqueConstraint(
            "kind", "reference_id", name="uq_creator_inbox_items_kind_reference_id"
        ),
    )
    with op.batch_alter_table("creator_inbox_items", schema=None) as batch_op:
        batch_op.create_index(
            "ix_creator_inbox_items_creator_user_id_event_at",
            ["creator_user_id", "event_at"],
            unique=False,
        )

    op.create_table(
        "idempotency_records",
        sa.Column("id", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column("user_id", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column("brand_id", sa.Uuid(native_uuid=False), nullable=True),
        sa.Column("method", sa.String(length=8), nullable=False),
        sa.Column("route_template", sa.String(length=255), nullable=False),
        sa.Column("key_digest", sa.String(length=64), nullable=False),
        sa.Column("request_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("response_status", sa.Integer(), nullable=True),
        sa.Column("response_headers", sa.Text(), nullable=True),
        sa.Column("response_ciphertext", sa.Text(), nullable=True),
        sa.Column("created_at", inspire_flow_backend.data.types.UTCDateTime(), nullable=False),
        sa.Column("completed_at", inspire_flow_backend.data.types.UTCDateTime(), nullable=True),
        sa.Column("expires_at", inspire_flow_backend.data.types.UTCDateTime(), nullable=False),
        sa.CheckConstraint(
            "status IN ('processing', 'completed', 'failed')",
            name=op.f("ck_idempotency_records_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["brand_id"],
            ["brand_organizations.id"],
            name=op.f("fk_idempotency_records_brand_id_brand_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_idempotency_records_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_idempotency_records")),
        sa.UniqueConstraint(
            "user_id",
            "brand_id",
            "method",
            "route_template",
            "key_digest",
            name="uq_idempotency_records_scope_key",
        ),
    )
    with op.batch_alter_table("idempotency_records", schema=None) as batch_op:
        batch_op.create_index("ix_idempotency_records_expires_at", ["expires_at"], unique=False)
        batch_op.create_index(
            "uq_idempotency_records_user_scope_key",
            ["user_id", "method", "route_template", "key_digest"],
            unique=True,
            sqlite_where=sa.text("brand_id IS NULL"),
        )

    op.create_table(
        "workshop_brand_authorizations",
        sa.Column("id", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column("creator_user_id", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column("brand_id", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column("active", sa.Boolean(), server_default=sa.text("1"), nullable=False),
        sa.Column("granted_at", inspire_flow_backend.data.types.UTCDateTime(), nullable=False),
        sa.Column("revoked_at", inspire_flow_backend.data.types.UTCDateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["brand_id"],
            ["brand_organizations.id"],
            name=op.f("fk_workshop_brand_authorizations_brand_id_brand_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["creator_user_id"],
            ["users.id"],
            name=op.f("fk_workshop_brand_authorizations_creator_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workshop_brand_authorizations")),
        sa.UniqueConstraint(
            "creator_user_id",
            "brand_id",
            name="uq_workshop_brand_authorizations_creator_user_id_brand_id",
        ),
    )
    with op.batch_alter_table("workshop_brand_authorizations", schema=None) as batch_op:
        batch_op.create_index(
            "ix_workshop_brand_authorizations_brand_id_active", ["brand_id", "active"], unique=False
        )

    op.create_table(
        "workshop_contacts",
        sa.Column("id", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column("workshop_user_id", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column("type", sa.String(length=24), nullable=False),
        sa.Column("label", sa.String(length=100), nullable=True),
        sa.Column("value_ciphertext", sa.Text(), nullable=False),
        sa.Column("visibility", sa.String(length=32), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("created_at", inspire_flow_backend.data.types.UTCDateTime(), nullable=False),
        sa.Column("updated_at", inspire_flow_backend.data.types.UTCDateTime(), nullable=False),
        sa.CheckConstraint(
            "type IN ('email','phone','wechat','qq','telegram','other')",
            name=op.f("ck_workshop_contacts_type_valid"),
        ),
        sa.CheckConstraint(
            "visibility IN ('private','authorized_brands')",
            name=op.f("ck_workshop_contacts_visibility_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["workshop_user_id"],
            ["creator_workshops.user_id"],
            name=op.f("fk_workshop_contacts_workshop_user_id_creator_workshops"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workshop_contacts")),
    )
    with op.batch_alter_table("workshop_contacts", schema=None) as batch_op:
        batch_op.create_index(
            "ix_workshop_contacts_workshop_user_id_sort_order",
            ["workshop_user_id", "sort_order"],
            unique=False,
        )

    op.create_table(
        "workshop_project_selections",
        sa.Column("id", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column("workshop_user_id", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column("project_id", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column("visibility", sa.String(length=32), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("created_at", inspire_flow_backend.data.types.UTCDateTime(), nullable=False),
        sa.Column("updated_at", inspire_flow_backend.data.types.UTCDateTime(), nullable=False),
        sa.CheckConstraint(
            "visibility IN ('private', 'workshop_public', 'brands_only', 'authorized_brands')",
            name=op.f("ck_workshop_project_selections_visibility_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_workshop_project_selections_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workshop_user_id"],
            ["creator_workshops.user_id"],
            name=op.f("fk_workshop_project_selections_workshop_user_id_creator_workshops"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workshop_project_selections")),
        sa.UniqueConstraint(
            "workshop_user_id",
            "project_id",
            name="uq_workshop_project_selections_workshop_user_id_project_id",
        ),
    )
    with op.batch_alter_table("workshop_project_selections", schema=None) as batch_op:
        batch_op.create_index(
            "ix_workshop_project_selections_workshop_user_id_sort_order",
            ["workshop_user_id", "sort_order"],
            unique=False,
        )

    op.create_table(
        "workshop_publications",
        sa.Column("id", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column("workshop_user_id", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("snapshot_json", sa.Text(), nullable=False),
        sa.Column("published_at", inspire_flow_backend.data.types.UTCDateTime(), nullable=False),
        sa.Column("updated_at", inspire_flow_backend.data.types.UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["workshop_user_id"],
            ["creator_workshops.user_id"],
            name=op.f("fk_workshop_publications_workshop_user_id_creator_workshops"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workshop_publications")),
        sa.UniqueConstraint(
            "workshop_user_id",
            "version",
            name="uq_workshop_publications_workshop_user_id_version",
        ),
    )
    with op.batch_alter_table("workshop_publications", schema=None) as batch_op:
        batch_op.create_index(
            "ix_workshop_publications_workshop_user_id_published_at",
            ["workshop_user_id", "published_at"],
            unique=False,
        )

    op.create_table(
        "workshop_social_accounts",
        sa.Column("id", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column("workshop_user_id", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column("platform", sa.String(length=32), nullable=False),
        sa.Column("handle", sa.String(length=120), nullable=True),
        sa.Column("profile_url", sa.String(length=2048), nullable=False),
        sa.Column("visibility", sa.String(length=32), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("created_at", inspire_flow_backend.data.types.UTCDateTime(), nullable=False),
        sa.Column("updated_at", inspire_flow_backend.data.types.UTCDateTime(), nullable=False),
        sa.CheckConstraint(
            "platform IN ('bilibili','douyin','xiaohongshu','weibo','zhihu','youtube','other')",
            name=op.f("ck_workshop_social_accounts_platform_valid"),
        ),
        sa.CheckConstraint(
            "visibility IN ('private', 'workshop_public', 'brands_only', 'authorized_brands')",
            name=op.f("ck_workshop_social_accounts_visibility_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["workshop_user_id"],
            ["creator_workshops.user_id"],
            name=op.f("fk_workshop_social_accounts_workshop_user_id_creator_workshops"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workshop_social_accounts")),
    )
    with op.batch_alter_table("workshop_social_accounts", schema=None) as batch_op:
        batch_op.create_index(
            "ix_workshop_social_accounts_workshop_user_id_sort_order",
            ["workshop_user_id", "sort_order"],
            unique=False,
        )

    op.create_table(
        "agent_turn_runs",
        sa.Column("id", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column("conversation_id", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column("user_id", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column("idempotency_record_id", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column("turn_id", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("result_ciphertext", sa.Text(), nullable=True),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("created_at", inspire_flow_backend.data.types.UTCDateTime(), nullable=False),
        sa.Column("completed_at", inspire_flow_backend.data.types.UTCDateTime(), nullable=True),
        sa.CheckConstraint(
            "status IN ('processing', 'completed', 'failed')",
            name=op.f("ck_agent_turn_runs_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["agent_conversations.id"],
            name=op.f("fk_agent_turn_runs_conversation_id_agent_conversations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["idempotency_record_id"],
            ["idempotency_records.id"],
            name=op.f("fk_agent_turn_runs_idempotency_record_id_idempotency_records"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_agent_turn_runs_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent_turn_runs")),
        sa.UniqueConstraint(
            "idempotency_record_id", name=op.f("uq_agent_turn_runs_idempotency_record_id")
        ),
        sa.UniqueConstraint("turn_id", name=op.f("uq_agent_turn_runs_turn_id")),
    )
    with op.batch_alter_table("agent_turn_runs", schema=None) as batch_op:
        batch_op.create_index(
            "ix_agent_turn_runs_conversation_id_created_at",
            ["conversation_id", "created_at"],
            unique=False,
        )

    op.create_table(
        "workshop_publication_contacts",
        sa.Column("id", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column("publication_id", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column("type", sa.String(length=24), nullable=False),
        sa.Column("label", sa.String(length=100), nullable=True),
        sa.Column("value_ciphertext", sa.Text(), nullable=False),
        sa.Column("visibility", sa.String(length=32), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["publication_id"],
            ["workshop_publications.id"],
            name=op.f("fk_workshop_publication_contacts_publication_id_workshop_publications"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workshop_publication_contacts")),
    )
    with op.batch_alter_table("workshop_publication_contacts", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_workshop_publication_contacts_publication_id"),
            ["publication_id"],
            unique=False,
        )

    op.create_table(
        "workshop_publication_project_cards",
        sa.Column("id", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column("publication_id", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column("source_project_id", sa.Uuid(native_uuid=False), nullable=True),
        sa.Column("title", sa.String(length=120), nullable=False),
        sa.Column("type", sa.String(length=50), nullable=False),
        sa.Column("audience", sa.String(length=500), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("icon_url", sa.String(length=2048), nullable=True),
        sa.Column("visibility", sa.String(length=32), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["publication_id"],
            ["workshop_publications.id"],
            name=op.f("fk_workshop_publication_project_cards_publication_id_workshop_publications"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_project_id"],
            ["projects.id"],
            name=op.f("fk_workshop_publication_project_cards_source_project_id_projects"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workshop_publication_project_cards")),
    )
    with op.batch_alter_table("workshop_publication_project_cards", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_workshop_publication_project_cards_publication_id"),
            ["publication_id"],
            unique=False,
        )

    op.create_table(
        "workshop_publication_social_accounts",
        sa.Column("id", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column("publication_id", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column("platform", sa.String(length=32), nullable=False),
        sa.Column("handle", sa.String(length=120), nullable=True),
        sa.Column("profile_url", sa.String(length=2048), nullable=False),
        sa.Column("visibility", sa.String(length=32), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["publication_id"],
            ["workshop_publications.id"],
            name=op.f(
                "fk_workshop_publication_social_accounts_publication_id_workshop_publications"
            ),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workshop_publication_social_accounts")),
    )
    with op.batch_alter_table("workshop_publication_social_accounts", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_workshop_publication_social_accounts_publication_id"),
            ["publication_id"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("workshop_publication_social_accounts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_workshop_publication_social_accounts_publication_id"))

    op.drop_table("workshop_publication_social_accounts")
    with op.batch_alter_table("workshop_publication_project_cards", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_workshop_publication_project_cards_publication_id"))

    op.drop_table("workshop_publication_project_cards")
    with op.batch_alter_table("workshop_publication_contacts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_workshop_publication_contacts_publication_id"))

    op.drop_table("workshop_publication_contacts")
    with op.batch_alter_table("agent_turn_runs", schema=None) as batch_op:
        batch_op.drop_index("ix_agent_turn_runs_conversation_id_created_at")

    op.drop_table("agent_turn_runs")
    with op.batch_alter_table("workshop_social_accounts", schema=None) as batch_op:
        batch_op.drop_index("ix_workshop_social_accounts_workshop_user_id_sort_order")

    op.drop_table("workshop_social_accounts")
    with op.batch_alter_table("workshop_publications", schema=None) as batch_op:
        batch_op.drop_index("ix_workshop_publications_workshop_user_id_published_at")

    op.drop_table("workshop_publications")
    with op.batch_alter_table("workshop_project_selections", schema=None) as batch_op:
        batch_op.drop_index("ix_workshop_project_selections_workshop_user_id_sort_order")

    op.drop_table("workshop_project_selections")
    with op.batch_alter_table("workshop_contacts", schema=None) as batch_op:
        batch_op.drop_index("ix_workshop_contacts_workshop_user_id_sort_order")

    op.drop_table("workshop_contacts")
    with op.batch_alter_table("workshop_brand_authorizations", schema=None) as batch_op:
        batch_op.drop_index("ix_workshop_brand_authorizations_brand_id_active")

    op.drop_table("workshop_brand_authorizations")
    with op.batch_alter_table("idempotency_records", schema=None) as batch_op:
        batch_op.drop_index(
            "uq_idempotency_records_user_scope_key",
        )
        batch_op.drop_index("ix_idempotency_records_expires_at")

    op.drop_table("idempotency_records")
    with op.batch_alter_table("creator_inbox_items", schema=None) as batch_op:
        batch_op.drop_index("ix_creator_inbox_items_creator_user_id_event_at")

    op.drop_table("creator_inbox_items")
    with op.batch_alter_table("brand_memberships", schema=None) as batch_op:
        batch_op.drop_index("ix_brand_memberships_user_id_brand_id")

    op.drop_table("brand_memberships")
    with op.batch_alter_table("brand_invitations", schema=None) as batch_op:
        batch_op.drop_index(
            "uq_brand_invitations_pending",
        )
        batch_op.drop_index("ix_brand_invitations_invited_user_id_status")
        batch_op.drop_index("ix_brand_invitations_brand_id_status")

    op.drop_table("brand_invitations")
    with op.batch_alter_table("brand_interests", schema=None) as batch_op:
        batch_op.drop_index(
            "uq_brand_interests_pending",
        )
        batch_op.drop_index("ix_brand_interests_creator_user_id_updated_at")
        batch_op.drop_index("ix_brand_interests_brand_id_status")

    op.drop_table("brand_interests")
    with op.batch_alter_table("brand_follows", schema=None) as batch_op:
        batch_op.drop_index("ix_brand_follows_creator_user_id_updated_at")
        batch_op.drop_index("ix_brand_follows_brand_id_status")

    op.drop_table("brand_follows")
    with op.batch_alter_table("creator_workshops", schema=None) as batch_op:
        batch_op.drop_index("ix_creator_workshops_status_updated_at")

    op.drop_table("creator_workshops")
    with op.batch_alter_table("brand_organizations", schema=None) as batch_op:
        batch_op.drop_index("ix_brand_organizations_updated_at")

    op.drop_table("brand_organizations")
    # ### end Alembic commands ###
